Throw differs in that instead of returning to the calling function, it will traverse the function stack until it finds a try statement